### ISSUE TITLE
AAAI foundation model paper examples

### ISSUE THREAD

**Issue by SFrav** [scallop-lang/scallop#27]
Is the code for the 2024 AAAI article by Ziyang Li et al. available online?
I have seen the CLUTRR code in the examples folder. Is this the kinship example from the paper? I'm particularly interested in experimenting with the OLW-ViT compositional VQA example to begin with.

P.S. really exciting work. Great to read the articles so far and see the codebase grow.

**Comment by Liby99** [comment]
Thanks for the inquiry. Please checkout the [examples](https://github.com/scallop-lang/scallop/tree/master/etc/scallop-cli/examples) directory within `scallop-cli`! Do let us know if the examples work (or do not work) for you!

**Comment by SFrav** [comment]
Thanks for the speedy response
