### ISSUE TITLE
Error with scallopy/history.py on latest commit

### ISSUE THREAD

**Issue by paulsushmita** [scallop-lang/scallop#28]
Hi there,

I took the latest pull of the repo, and seems like there is a broken link to scallopy/history.py (probably the reorganization of files to scallopy/utils/history.py led to this). 

Thanks,
Sushmita

**Comment by Liby99** [comment]
Thanks for the report. However I can't seem to locate the issue as I don't see any direct reference of `scallopy/history.py`. Would you mind doing a fresh build of the repository (maybe by removing your old version) and report back if the issue still exists? Meanwhile, what is the exact location where the error is thrown? A concrete exception stack trace would be really helpful. Thanks so much in advance.

**Comment by paulsushmita** [comment]
Thank you for the prompt response.

I ran a `make clean` before building scallopy this time and it worked fine.

Thanks for the suggestion.
