### ISSUE TITLE
Discussion: Adding relation schema for derived rules is optional? 

### ISSUE THREAD

**Issue by RAbraham** [scallop-lang/scallop#36]
Hi, 
In the following code, I didn't have to define a relation for `man`. It still worked. That is very convenient. But if I look at the `scc` example, I see that relation is defined for derived relations like `path` and `scc`. I just wanted to know if there are any pitfalls in not defining relations for derived relations. 

```python
#man.py
import scallopy

ctx = scallopy.ScallopContext()

# Setup the context by adding relations and facts

ctx.add_relation("species", (str, str))
ctx.add_facts("species", [("Abe", "man"), ("Bob", "man"), ("Samba", "animal")])
ctx.add_rule("man(a) = species(a, \"man\")")

# Run the scallop program
ctx.run()

# Print the result
print(list(ctx.relation("man")))

```

```shell
>  python man.py          
[('Abe',), ('Bob',)]

```

**Comment by Liby99** [comment]
Thanks for the question!

Basically the difference is whether you want to rely on Scallop's type inference module to help you infer the type of "derived relations". In my examples I tend to make things explicit. In other cases, I will define those relations if I have a specific type constraint that I want to impose on the program. I don't think there is any other pitfalls in not defining those relations.

In your example, the type of the relation `man` is easily inferable. And that is why you don't need such a type definition.

**Comment by RAbraham** [comment]
good to know. I'm very happy that this feature exists :). Thanks!
